site_name: Deck of Adventures
site_url: https://www.DeckofAdventures.com/
site_description: Deck of Adventures Documents
site_author: CBroz1

repo_url: https://github.com/CBroz1/TheGame
edit_uri: docs/

theme:
    name: cinder
    custom_dir: ./docs/theme/
    pallette:
        scheme: slate
    features:
      - navigation.sections
      - navigation.expand
      - navigation.top
    disable_nav_previous_next: true
    disable_nav_search: false
    locale: en
    nav-style: dark
    shortcuts:
        help: 191    # ?
        next: 78     # n
        previous: 80 # p
        search: 83   # s
    # analytics: {gtag: 'G-274394082'}

nav:
    - index.md
    - Mechanics:
        - 1_Mechanics/01_PlayerGuide_Brief.md
        - 1_Mechanics/01_PlayerGuide_Full.md
        - 1_Mechanics/02_GMGuide.md
        - 1_Mechanics/03_CharacterCreation.md
        - 1_Mechanics/04_Powers.md
        - 1_Mechanics/05_Vulnerabilities.md
        - 1_Mechanics/99_Glossary.md
        - 1_Mechanics/Circlular_TC-DR_Tool/README.md
        - 1_Mechanics/PremadeCharacters/README.md
    - Development:
        - 2_Development/01_Community.md
        - 2_Development/02_Design_Document.md
        - CHANGELOG.md
        - CONTRIBUTING.md
        - CODE_OF_CONDUCT.md

extra_css:
    - theme/extra.css

plugins:
    - search
    - exclude:
        glob:
          - "temp*"
          - "3_Automation/*"
    # - include-markdown # https://github.com/mondeja/mkdocs-include-markdown-plugin
    # when use, add mkdocs-include-markdown-plugin to pip list
