blank_issues_enabled: true
contact_links:
  - name: Deck of Adventure Contribution Guideline
    url: https://github.com/DeckofAdventure/beta/blob/main/CONTRIBUTING.md
    about: Please make sure to review the Deck of Adventure Contribution Guidelines
