blank_issues_enabled: true
contact_links:
  - name: Deck of Adventures Contribution Guideline
    url: https://github.com/DeckofAdventures/TheGame/blob/main/CONTRIBUTING.md
    about: Please make sure to review the Deck of Adventures Contribution Guidelines
