site_name: Deck of Adventures
site_url: https://www.DeckofAdventures.com/
site_description: Deck of Adventures Documents
site_author: CBroz1

repo_url: https://DeckofAdventures.github.io//TheGame
docs_dir: ./src/
# edit_uri: docs/

theme:
    name: material
    custom_dir: overrides
    features:
      - toc.integrate
      - navigation.sections
      - navigation.expand
      - navigation.top
    palette:
      - media: "(prefers-color-scheme: light)"
        scheme: my-default
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        toggle:
          icon: material/brightness-4
          name: Switch to light mode
    disable_nav_previous_next: true
    disable_nav_search: false
    locale: en
    shortcuts:
        help: 191    # ?
        next: 78     # n
        previous: 80 # p
        search: 83   # s
    analytics: {gtag: 'G-NVDBHE89HX'}

nav:
  # - Home: README.md
  - Mechanics:
    - Brief Guide:          1_Mechanics/01_PlayerGuide_Brief.md
    - Full Guide:           1_Mechanics/01_PlayerGuide_Full.md
    - GM Guide:             1_Mechanics/02_GMGuide.md
    - Character Creation:   1_Mechanics/03_CharacterCreation.md
    - Powers:               1_Mechanics/04_Powers.md
    - Vulnerabilities:      1_Mechanics/05_Vulnerabilities.md
    - Glossary:             1_Mechanics/99_Glossary.md
    - Lookup Tool:          1_Mechanics/Circlular_TC-DR_Tool/README.md
    - Premades:             1_Mechanics/PremadeCharacters/README.md
  - Development:
    - Community:            2_Development/01_Community.md
    - Design:               2_Development/02_Design_Document.md
    - Change Log:           CHANGELOG.md
    - Contributions:        CONTRIBUTING.md
    - Code of Conduct:      CODE_OF_CONDUCT.md

extra_css:
  - stylesheets/extra.css

plugins:
    - search
    - exclude:
        glob:
          - "temp*"
          - "3_Automation/*"
    # - include-markdown # https://github.com/mondeja/mkdocs-include-markdown-plugin
    # when use, add mkdocs-include-markdown-plugin to pip list

markdown_extensions:
  - attr_list
  - toc:
      permalink: true

extra:
  generator: false # Disable watermark
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/DeckofAdventures/
    - icon: fontawesome/brands/discord
      link: https://discord.gg/dk6RfWgPHF
