name: build
on:
  push:
    branches:
      - page-test
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs mkdocs-cinder mkdocs-exclude
      # later: add mkdocs-include-markdown-plugin to pip list
      # Copy root dir items to docs when publishing
      - run: for f in C*md; do cp $f ./docs/; done
      # not sure if below actually works
      - run: iconv -f utf-8 -t utf-8 -c ./docs/1_Mechanics/04_Powers.md -o ./docs/1_Mechanics/04_Powers.md
      - run: mkdocs gh-deploy --force --clean --verbose
