name: build
on:
  pull_request:      # close of PR. Insufficient permissions?
    branches:
      - main
    types:
      - closed
  push:              # on pushing to page-test, as a dev branch for forks only
    branches:
      - page-test
  workflow_dispatch: # on clicking browser GUI button - Not working?

permissions:
  contents: write
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          
      - name: Set up Python runtime
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup - pip & config
        run: | # Later: mkdocs-include-markdown-plugin
          for f in C*md; do cp $f ./docs/src/; done 
          cp LICENSE ./docs/src/
          pip install mkdocs-material mkdocs-exclude mkdocs-gen-files mike
          git config user.name 'github-actions[bot]' && git config user.email 'github-actions[bot]@users.noreply.github.com'
      
      - name: Deploy
        run: |
          bash ./docs/docs.sh 
          git push https://github.com/CBroz1/TheGame.git gh-pages # EDIT!
        env:
          USERNAME: github-actions[bot]
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOOGLE_ANALYTICS_KEY: ${{ secrets.GOOGLE_ANALYTICS_KEY }}

